### ISSUE TITLE
[Aurora Testnet] Deposit from Ropsten to Aurora is extremely slow

### ISSUE THREAD

**Issue by danielwpz** [aurora-is-near/rainbow-bridge#608]
hey,

I tried to deposit 1 ETH from ropsten to aurora testnet, this is the transaction on ropsten: https://ropsten.etherscan.io/tx/0x6d91dc4f641e0afd2dfcde44ea59b30367fe57c5b97361f18d01f61beece0f7b , which has been confirmed 1 day ago. However on aurora the transaction is still under processing now and my account balance in aurora is not updated.

If anyone can take a look at this issue it'll be really appreciated.

**Comment by mfornet** [comment]
Ropsten bridge had been very unstable lately, and because of that we have restarted couple of time to catch-up. Unfortunately we don't give any warranties between Ropsten and Near testnet since Ropsten POW goes into really deep reorgs which the bridge can't handle gracefully. At this point your Ropsten Eth is locked in the bridge contract and can't be easily recovered.

We have some Ropsten Eth, so I can refund it, if you share an address with me.
